### ISSUE TITLE
Add golden files for TPC-H/TPC-DS suites

### ISSUE THREAD

**Issue by sunchao** [apache/arrow-datafusion-comet#10]
We currently have a bunch of TPC-H/TPC-DS test suites including `CometTPCDSQuerySuite`, `CometPlanStabilitySuite`, etc. In order to use these, we need to add the golden files generated via Comet first.

**Comment by viirya** [comment]
This is blocked by #8

**Comment by sunchao** [comment]
Hmm, I thought we just need to generate the files locally?

**Comment by viirya** [comment]
I thought you want run these test suite, e.g., `CometTPCDSQuerySuite`, `CometPlanStabilitySuite`, on CI?

**Comment by viirya** [comment]
Without the CI pipeline, it seems no much sense to include these golden files.

**Comment by sunchao** [comment]
Right, in that sense it is more related to #7. #8 is to run SQL tests in Spark itself.
