### ISSUE TITLE
Build with Java 21 failed

### ISSUE THREAD

**Issue by Abhishek-Mohan** [apache/arrow-datafusion-comet#129]
### Describe the bug

When trying to build with Java 21, it fails during org.apache.comet:comet-common-spark3.4_2.12 step. 
There looks to be some issue between SBT and Scala as this is the error.

`[INFO] --- scala:4.7.2:compile (scala-compile-first) @ comet-common-spark3.4_2.12 ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /Users/abhishekmohan/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.7.1-bin_2.12.17__65.0-1.7.1_20220712T022208.jar
[INFO] Compiler bridge file is not installed yet
error:
  bad constant pool index: 0 at pos: 48461
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.12.17
    compiler version: version 2.12.17
`

### Steps to reproduce

1. Install Jdk17 and set it as the default
2. Run `make release PROFILES="-Pspark-3.4"`

### Expected behavior

It should build successfully.

### Additional context

Java 17 builds successfully, so wanted to surface this issue as I saw no prior issue raised for this.

**Comment by sunchao** [comment]
I don't think Spark 3.4 supports Java 21 yet, so that may be the issue. See https://issues.apache.org/jira/browse/SPARK-43831 for the minimum Scala version required for 21.

**Comment by Abhishek-Mohan** [comment]
Ah thanks for pointing that out. It looks like only Spark 4.0 will support Java 21, not Spark 3.4 nor Spark 3.5. I'll close this issue, as until Spark 4.0 is released, Java 21 won't even be supported.
