### ISSUE TITLE
Support Spark bloom filter expression BloomFilterMightContain

### ISSUE THREAD

**Issue by viirya** [apache/arrow-datafusion-comet#145]
### What is the problem the feature request solves?

While I checked query plans of other works, I found there are some TPC-H queries (e.g., q2, q5, q7, q8) containing bloom filter expression `BloomFilterMightContain` which blocks Comet transforming Spark query plan. We should support it to unblock these part of queries.

**Comment by singhpk234** [comment]
can i pick this up ?

**Comment by viirya** [comment]
Sure. Feel free to take the issues no one claims working on it. Thank you.

**Comment by viirya** [comment]
@advancedxy 

Hmm, thanks for the contribution. However, could you make sure what you plan to do and claim in the related ticket? I'm asking this because you claim you will/want to do some other tickets (more than one) but you never say you will or are working in this. You can see there is other one picking this available ticket yesterday.

A clear claim of the willing to work on tickets would be good to community collaboration. For example, others probably are interested in the tickets you said you want to work but cannot work on the tickets due to that. And, this ticket is available and the one picked it up yesterday might already work on it.

Thank you.

**Comment by viirya** [comment]
Thank you @advancedxy . Appreciate your understanding and your contribution so far!

**Comment by singhpk234** [comment]
> @singhpk234 Sorry, I didn’t notice that you are claiming this issue when I actually started the work. If your work is almost done, I can close my pr in favor of yours since you claimed it first. If you barely start it, I would appreciate your input on my current pr.

@advancedxy i was in the middle, was done with spark changes and was about to start rust changes. I see you have complete implementation out, i think it would be better to go ahead with your pr, rather than closing it now, it's just that my efforts got wasted. It would have been better if you would have just commented on the ticket rather than just directly submitting the pr. But no issues :), All good !

Looking forward to contributing more with you !

**Comment by viirya** [comment]
Thanks @singhpk234 for your effort. Feel free to take any other available tickets you are interested.
