### ISSUE TITLE
Set up RAT checks in CI

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion-comet#3]
Once the initial PR is merged, we should add [RAT](https://creadur.apache.org/rat/) checks in CI before we start merging new PRs.

**Comment by andygrove** [comment]
@sunchao Can someone on your team take a look at this? Hopefully, you can copy the GitHub workflow from DataFusion for the Rust code, and reference Apache Spark for the maven part.

**Comment by sunchao** [comment]
Sure, will do. Yes I looked at the RAT tool in DF and we can pretty much reuse it I think

**Comment by sunchao** [comment]
I think we already have something in the CI to do the check. For instance [here](https://github.com/apache/arrow-datafusion-comet/actions/runs/7997958755/job/21843358232).

The check is done by the [rat plugin](https://github.com/apache/arrow-datafusion-comet/blob/main/pom.xml#L801) and is applied to all files in the repo.

**Comment by andygrove** [comment]
Thanks @sunchao. I will close this issue.
