### ISSUE TITLE
Introduce unified memory manager

### ISSUE THREAD

**Issue by sunchao** [apache/arrow-datafusion-comet#34]
### What is the problem the feature request solves?

Currently Comet has separate memory management from JVM and native: on JVM side, it uses Spark's memory manager, while on native side, it uses DF's memory manager. This poses an issue when we have both Spark and native operators in a single query, since the split is static and we cannot request & spill memory from native to JVM, or vice versa.

In contrast, Photon uses Spark's memory manager to manage memory from both JVM and native:

> Photon and Apache Spark share the same cluster and thus must have a consistent view of memory and disk usage to avoid being OOM-killed by the OS or the JVM. As a result, Photon hooks into Apache Spark’s memory manager. To handle this, we separate the concept of memory reservations from allocations in Photon. A memory reservation asks for memory from Spark’s unified memory manager. Like all requests to the memory manager, this can cause a spill, where Spark asks some memory consumer to release memory to satisfy a new request. Photon hooks into this memory consumer API, so Spark can ask Photon to spill data on behalf of other memory-consuming operators that are executing (e.g., a sort task in Spark may ask a Photon operator to spill). Similarly, Photon can make reservations that cause other Spark operators to spill, or cause Photon itself to spill (leading to a “recursive spill” where one Photon operator spills memory on behalf of another one). This differs slightly from many other database engines, where operators are given a fixed memory budget and can only “self-spill.” Spilling is dynamic because we often do not have information on how much data an operator will consume, especially if SQL operators are co-existing with user-defined code that also reserves memory. We use the same policy as open source Apache Spark to determine which operator to spill. To summarize, if we need to spill 𝑁 bytes to satisfy a memory reservation request, we sort the memory consumers from least to most allocated memory, and spill the first consumer that holds at least 𝑁 bytes. The rationale behind this is that we minimize the number of spills and avoid spilling more data than necessary. After reserving memory, Photon can allocate memory safely without spilling. Allocation is purely local to Photon: Spark only accounts for the memory that Photon asks for. In spilling operators such as hash join and grouping aggregation the processing of an input batch is thus broken up into two phases: a reservation phase where memory is acquired for the new input batch and spilling is handled, and an allocation phase where transient data can be produced since no spilling can occur. This flexible spilling mechanism has been critical in the Lakehouse context, where queries often exceed the available memory

In particular:

> Photon hooks into this memory consumer API, so Spark can ask Photon to spill data on behalf of other memory-consuming operators that are executing (e.g., a sort task in Spark may ask a Photon operator to spill). Similarly, Photon can make reservations that cause other Spark operators to spill, or cause Photon itself to spill (leading to a “recursive spill” where one Photon operator spills memory on behalf of another one)

which is a better approach. Note the pre-requisite for this is that the memory manager should be using off-heap memory, so that it can be shared between JVM and native.

On Comet side, DF already supports a pluggable memory manager through its [memory_pool](https://github.com/apache/arrow-datafusion/tree/main/datafusion/execution/src/memory_pool) API. This allows us to implement an adapter class on the Java side to delegate the calls to Spark's memory manager via JNI. 

Unlike Spark, DF doesn't trigger spilling from registered memory consumers when under pressure (removed via https://github.com/apache/arrow-datafusion/pull/4522). This means the behavior will differ depending on whether the memory consumer is on the JVM side or native side: when a memory consumer is requesting more memory than currently available, the memory manager will trigger spill from memory consumers from the JVM, but not native.

Another requirement is for Spark to switch to use off-heap memory when the unified memory manager is active. By default, Spark uses on-heap memory, so this will require configuration changes from users, which is inconvenient. We could leverage Spark's `DriverPlugin` to overwrite memory setting so this transition becomes transparent. For instance, if user set `spark.executor.memory` to be 64G. The driver plugin could overwrite the memory setting to be:
- `spark.memory.offHeap.enabled`: true
- `spark.executor.memory`: 64 * 0.3
- `spark.memory.offHeap.size`: 64 * (1 - 0.3)

This assumes we have a configuration `spark.comet.memory.onHeap.fraction` which specifies how much memory should be reserved for on-heap. The value is 0.3 in the above example.

### Describe the potential solution

Introduce a new `memory_pool` implementation for Comet, which forwards the memory allocation / deallocation calls to the Spark's unified memory manager instance.

**Comment by sunchao** [comment]
At the moment in Spark, `DriverPlugin` is initialized before `MemoryManager`, `ResourceProfileManager`. Therefore, it is not possible to override the memory settings unless we change the initialization order.

**Comment by singhpk234** [comment]
> Introduce a new memory_pool implementation for Comet, which forwards the memory allocation / deallocation calls to the Spark's unified memory manager instance.

+1, do you have something for this already ? if not i would love to help / contribute

**Comment by sunchao** [comment]
Hi @singhpk234 , thanks for your interest! Yes we do have something internally that's going to be open sourced soon. Will update this Github issue soon.
