### ISSUE TITLE
Support build with Java 1.8

### ISSUE THREAD

**Issue by advancedxy** [apache/arrow-datafusion-comet#43]
### What is the problem the feature request solves?

Currently, the main branch cannot build with Java 1.8. The first issue when building with Java 1.8 is as follows:
```
[ERROR] Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision (get-the-git-infos) on project comet-common-spark3.4_2.12: Execution get-the-git-infos of goal io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0:revision failed: Unable to load the mojo 'revision' in the plugin 'io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: pl/project13/maven/git/GitCommitIdMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This is because git-commit-id-maven-plugin dropped Java 1.8 support in 5.0.0. There are other various errors that doesn't work with Java 1.8.

However, in the README, it indicates that it only requires JDK 8 and up
https://github.com/apache/arrow-datafusion-comet/blob/main/README.md#requirements

Do you think is it worthy to make comet support JDK 8? I think it would be beneficial to support JDK 8 as Spark itself still supports JDK 8 in 3.5 and it's only dropped in the up-coming 4.0 release.

### Describe the potential solution

1. downgrade the plugin version to be compatible with JDK 8
2. various changes to make code compiles with JDK 8
3. set-up ci to build and run with JDK 8

**Comment by viirya** [comment]
For 2 that changes to code for code compliance with JDK8. If the change is relatively large, I would suggest hold it until we open source all internal patches otherwise the possible conflicts might hinder porting.
