### ISSUE TITLE
Write a blog post about the comet donation

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion-comet#6]
Now that the initial donation of comet has been completed https://github.com/apache/arrow-datafusion-comet/pull/1, I think it would help the project to write a blog post about the donation

I think similar blogs helped the DataFusion and Ballista donation to gain attention

https://arrow.apache.org/blog/2019/02/04/datafusion-donation/
https://arrow.apache.org/blog/2021/04/12/ballista-donation/

**Comment by alamb** [comment]
I would be happy to help collaborate on this post / lead the effort as I think it directly helps the DataFusion evangelism

**Comment by alamb** [comment]
cc @sunchao @viirya

**Comment by viirya** [comment]
We currently open sourced part of Comet. Some other parts of Comet are still waiting for internal evaluation process. I'm wondering if we want to write the blog after all parts of Comet are open sourced?

**Comment by alamb** [comment]
> We currently open sourced part of Comet. Some other parts of Comet are still waiting for internal evaluation process. I'm wondering if we want to write the blog after all parts of Comet are open sourced?

I think writing the blog will serve to draw attention to DataFusion and comet. 

To make the most of the publicity, I think we should have a good story about how people can contribute / try it out if they want. So for example, what types of features / help are most valuable? For example, maybe spark compatible date functions (I am pretty sure there are others who are interested in this too)

In any event, I think we should draft the blog post and then we can decide when to publish it based on whatever else is in the pipeline.

I'll try and throw together a draft over the next week or so
