### ISSUE TITLE
Speedup CI and reduce test run time

### ISSUE THREAD

**Issue by advancedxy** [apache/arrow-datafusion-comet#67]
### What is the problem the feature request solves?

It looks like that CIs are quite slow, the most time consuming parts varies from 60m to 100+m.
<img width="844" alt="image" src="https://github.com/apache/arrow-datafusion-comet/assets/807537/2ac0b0e2-2773-486d-b04d-5159a4801e57">

It would be great that we could speed them up and hopefully keep them under ~30m.

**Comment by sunchao** [comment]
We can probably split the shuffle related tests into separate CI jobs

**Comment by sunchao** [comment]
... or reduce the amount of data in shuffle, right now it is 10000 in many tests.

**Comment by sunchao** [comment]
@advancedxy @viirya what do you think if we move all the MacOS CI pipelines to post-commit, and only keep the `ubuntu-latest` pipelines as pre-commit? It seems the former are pretty slow especially with Java 8, while the latter are usually faster (~40min). 

I think having `ubuntu-latest` should be sufficient to catch any potential issue in the PRs.

**Comment by viirya** [comment]
Okay for me. If we find any thing wrong withe Mac OS, we can take action after commit to revert it or fix it.

**Comment by sunchao** [comment]
OK, let's keep `ubuntu-latest` and MacOS Apple Silicon in the pre-commit then, and move MacOS X86 to post-commit. I'm also making changes in #109 to improve the test time in shuffle & aggregation. Will ping you once it is ready.
