### ISSUE TITLE
MacOS (x86_64) CI is flaky with libcrypto issue

### ISSUE THREAD

**Issue by sunchao** [apache/arrow-datafusion-comet#76]
### Describe the bug

Github CI for MacOS x86_64 is currently flaky with message:

```
WARNING: /Users/runner/hostedtoolcache/Java_Zulu_jdk/8.0.402-6/x64/jre/bin/java is loading libcrypto in an unsafe way
```

Some attempts have been made in #55 and #41, but it is still not resolved.

### Steps to reproduce

Check the post-commit CI runs and occasionally it still fails with the above message.

### Expected behavior

The CI for MacOS x86_64 should pass consistently.

**Comment by viirya** [comment]
Have we tried https://stackoverflow.com/questions/72235813/openjdk8-java-is-loading-libcrypto-in-an-unsafe-way-in-macos-monterey?
